apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: ConsoleNotification
      name: classification-banner-top
    patch: |-
      - op: replace
        path: /spec/text
        value: 'Red Hat Device Edge - Demo Cluster'